# Generated by Django 5.0.3 on 2024-03-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'CEO'), (1, 'Teacher'), (2, 'Student')], default=2),
        ),
    ]
