# Generated by Django 5.0.3 on 2024-03-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_question_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Science',
            new_name='Sciences',
        ),
    ]
