# Generated by Django 5.0.3 on 2024-03-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_science_sciences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sciences',
            new_name='Science',
        ),
    ]
